$controller_script = <<-'SCRIPT'
        sudo ufw disable
        sudo apt-get install nfs-common
        echo 'Installing k3s'
        export INSTALL_K3S_EXEC="--bind-address=192.168.56.110 --flannel-iface=eth1"
        curl -sfL https://get.k3s.io | sh -
        while ! sudo systemctl is-active --quiet k3s; do 
          echo "Waiting for k3s to become active..."
          sleep 5
        done
        echo 'Adjusting permissions for k3s.yaml'
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        sudo cp /vagrant_shared/*.yaml .
        sudo kubectl apply -f .
        SCRIPT

Vagrant.configure("2") do |config|
  
  config.vm.define "hkrifaS" do |hkrifaS|
    hkrifaS.vm.box = "generic/ubuntu1804"
    hkrifaS.vm.hostname = "hkrifaS"
    hkrifaS.vm.network "private_network", ip: "192.168.56.110"
    hkrifaS.vm.synced_folder "./confs", "/vagrant_shared", type: "nfs", nfs_version: 4, nfs_udp: false
    hkrifaS.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", "hkrifaS"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id,"--natdnsproxy1", "on"]
    end
    hkrifaS.vm.provision "shell", inline: $controller_script
  end
end