$controller_script = <<-'SCRIPT'
        sudo ufw disable
        sudo apt-get install nfs-common
        echo 'Installing k3s'
        export INSTALL_K3S_EXEC="--bind-address=192.168.56.110 --flannel-iface=eth1"
        curl -sfL https://get.k3s.io | sh -
        while ! sudo systemctl is-active --quiet k3s; do 
          echo "Waiting for k3s to become active..."
          sleep 5
        done
        echo 'copy token'
        sudo cp /var/lib/rancher/k3s/server/token /vagrant_shared/token
        echo 'Adjusting permissions for k3s.yaml'
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        SCRIPT

$worker_script = <<-'SCRIPT'
        sudo ufw disable
        sudo apt-get install nfs-common
        export K3S_TOKEN_FILE="/vagrant_shared/token"
        export K3S_URL=https://192.168.56.110:6443
        export INSTALL_K3S_EXEC="--flannel-iface=eth1"
        curl -sfL https://get.k3s.io | sh -
        SCRIPT

Vagrant.configure("2") do |config|
  
    config.vm.define "hkrifaS" do |hkrifaS|
      hkrifaS.vm.box = "generic/ubuntu2004"
      hkrifaS.vm.hostname = "hkrifaS"
      hkrifaS.vm.network "private_network", ip: "192.168.56.110"
      hkrifaS.vm.synced_folder "./shared", "/vagrant_shared", type: "nfs", nfs_version: 4, nfs_udp: false
      hkrifaS.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", "hkrifaS"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id,"--natdnsproxy1", "on"]
      end
      hkrifaS.vm.provision "shell", inline: $controller_script
    end

    config.vm.define "hkrifaSW" do |hkrifaSW|
      hkrifaSW.vm.box = "generic/ubuntu2004"
      hkrifaSW.vm.hostname = "hkrifaSW"
      hkrifaSW.vm.network "private_network", ip: "192.168.56.111"
      hkrifaSW.vm.synced_folder "./shared", "/vagrant_shared", type: "nfs", nfs_version: 4, nfs_udp: false
      hkrifaSW.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--name", "hkrifaSW"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
      hkrifaSW.vm.provision "shell", inline: $worker_script
    end
  end